name: Build project
on:
  push:
    branches: ['**']
jobs:
  build:
    name: Emulate build
    runs-on: ubuntu-latest
    steps:
      - run: echo $EVENT | jq
        env:
          EVENT: ${{ toJSON(github.event) }}
